# Site Settings
title: Grant T. Aguinaldo // Data Analyst
url: 'http://webjeda.com'
baseurl: '/resume' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
style: styles-5
#style: styles-6


#Profile information
name: Grant T. Aguinaldo
tagline: Data Analyst
pic: GTA-Headshot-100x100.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'A data-driven collaborator who makes decisions based off of seemingly unrelated facts/data and can communicate the results to stakeholders in plain english. A professional with broad range of skills and knowledge of business operations in different industries who can bring high-level visions to reality using a variety of modern-day tools and techniques.'

#sidebar links
email: grant.aguinaldo@gmail.com
phone: 1+ 415 203 0520
website: grantaguinaldo.com #do not add http://
linkedin: grantaguinaldo
github: grantaguinaldo
twitter: '@grantaguinaldo'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
